### ISSUE TITLE
remove deafult streams, add own, change user name password etc

### ISSUE THREAD

**Issue by cctvuseruk** [chromakode/streamwall#11]
hi, where are the default streams located, how to remove them and only add my own, how to change user name and password etc

**Comment by sean1138** [comment]
username and password are in \streamwall\package.json - look for
`--username=woke --password=woke`

default/preloaded streams get pulled from a google doc here:
https://woke.net/#streams
and somehow gets put into a json file but i can't explain how that works.

\streamwall\src\node\data.js has
`const publicDataURL = 'https://woke.net/api/streams.json'`
and there are several references to the google doc's URL in the files.

**Comment by cctvuseruk** [comment]
thank you for your response, thathas helped, what i ment was, is it possible to remove all the woke feeds that get pulled from the google doc, and add my own, example i want to add 5 of my own feeds and save them - not use the woke ones, only my own?

**Comment by chromakode** [comment]
Hey, thanks for your interest! You can use the "custom streams" UI at the bottom of the window to add your own streams. They're not currently persisted, but that is something I have on the [roadmap](https://github.com/chromakode/streamwall/projects/1#card-40562279).

I'd also like to make the data source configurable. This depends on the kinds of use cases folks have, so I'd appreciate help designing and implementing this functionality. In the short term there's some other tasks to improve the quality of the stream that will take priority, but this is something I'd like to improve in the future. If someone wanted to work on implementing these changes I'd be happy to advise!

**Comment by cctvuseruk** [comment]
love your response!! a urgent thing that is needed, is to have a feature like obs interact - we really need to be able to change the bit rate of feeds, i had so many pushing full 1080p high bit rate which is not really needed at all times, please work on something that will allow us to lower bit rates of each feed, i love stream wall

**Comment by chromakode** [comment]
Custom data source URLs (and sourcing streams from a file) are now supported (as of https://github.com/chromakode/streamwall/commit/b2215aa42d8b55b5f0b78778ff53f7b889313df9). Docs here: https://github.com/chromakode/streamwall#data-sources
