### ISSUE TITLE
Change size of grid (4x4, 8x8, etc)

### ISSUE THREAD

**Issue by evilalmus** [chromakode/streamwall#12]
It would be really nice to be able to change the size of the grid, 4x4, 8x8, etc. It would allow for much more flexibility for oddly shaped and sized sources.

**Comment by chromakode** [comment]
Great idea! It's halfway doable right now, will just require a little
plumbing to make it configurable. 👍

**Comment by evilalmus** [comment]
I just figured out that this feature is basically already there, you just have to edit the constants.js file, however the control interface shows the 3x3 grid no matter what you set so there is no way to control the larger grid. I would think this should be a fairly easy change, it's just not in my scope of ability ;)

**Comment by chromakode** [comment]
Now available in https://github.com/chromakode/streamwall/commit/a0fcc4e8a86207f9cf5ade0dcb5e4e0f7e6de995!
