### ISSUE TITLE
Add configuration for spreadsheet URL

### ISSUE THREAD

**Issue by sayhiben** [chromakode/streamwall#30]
**Overview**
Streamwall currently reads from a hardcoded URL to pull livesheet data from that is specific to WOKE. Other users of streamwall and sheets2json host their livesheet data at different URLs. It would be nice to be able to configure the URL of the livesheet data instead of updating the hardcoded string

**Acceptance criteria**
- Streamwall reads the livesheet URL from configuration/options rather than using a hardcoded URL

**Comment by chromakode** [comment]
This is possible as of last night: https://github.com/chromakode/streamwall/commit/b2215aa42d8b55b5f0b78778ff53f7b889313df9. You can also use a file as a data source. :grin:
